version: '3.1'

services:
  shrinker:
    build: ./
    ports:
      - 8082:3000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: urlsDB
      POSTGRES_USER: mac
      POSTGRES_PASSWORD: 123456

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
